### PR TITLE
Explain time measured in cycles, fixed frequency.

### PR DESCRIPTION
**Pull request by rwatson**
Answer a question raised in #4 relating to execution times used to calculate overheads.

### CODE REVIEW

**Comment by rwatson** [comment]
Tagging @ltratt as a potential reviewer for this patch -- does this fully answer your question(s) about units, or is more needed?

**Review by brooksdavis — COMMENTED** [review]
It might be worth explicitly mentioning that there is no possibility of thermal throttling on the FPGA.

**Comment by ltratt** [comment]
@brooksdavis has just answered the question I was about to type!

**Comment by rwatson** [comment]
See if this tweak helps?

**Review by brooksdavis — APPROVED** [review]

**Pull request merged**
